[2023-09-27T06:19:09.412+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_DAG.load_task manual__2023-09-27T06:19:07.510910+00:00 [queued]>
[2023-09-27T06:19:09.416+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_DAG.load_task manual__2023-09-27T06:19:07.510910+00:00 [queued]>
[2023-09-27T06:19:09.416+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-27T06:19:09.456+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): load_task> on 2023-09-27 06:19:07.510910+00:00
[2023-09-27T06:19:09.458+0000] {standard_task_runner.py:57} INFO - Started process 55554 to run task
[2023-09-27T06:19:09.460+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_DAG', 'load_task', 'manual__2023-09-27T06:19:07.510910+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/load_dag.py', '--cfg-path', '/tmp/tmpa3517syp']
[2023-09-27T06:19:09.460+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask load_task
[2023-09-27T06:19:09.739+0000] {task_command.py:415} INFO - Running <TaskInstance: load_DAG.load_task manual__2023-09-27T06:19:07.510910+00:00 [running]> on host codespaces-4967f6
[2023-09-27T06:19:09.834+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_DAG' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T06:19:07.510910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-27T06:19:07.510910+00:00'
[2023-09-27T06:19:09.835+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-27T06:19:09.835+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ". separator ","\n.import --skip 1 /workspaces/hands-on-introduction-data-engineering-4395021/         lab/orchestrated/airflow-data-transformed.csv top_level_domains" | sqlite3 /workspaces/hands-on-introduction-data-engineering-4395021/             lab/orchestrated/airflow-load-db.db']
[2023-09-27T06:19:09.839+0000] {subprocess.py:86} INFO - Output:
[2023-09-27T06:19:09.841+0000] {subprocess.py:93} INFO - Error: unable to open database "/workspaces/hands-on-introduction-data-engineering-4395021/": unable to open database file
[2023-09-27T06:19:09.841+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-27T06:19:09.845+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-27T06:19:09.847+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=load_DAG, task_id=load_task, execution_date=20230927T061907, start_date=20230927T061909, end_date=20230927T061909
[2023-09-27T06:19:09.886+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 104 for task load_task (Bash command failed. The command returned a non-zero exit code 1.; 55554)
[2023-09-27T06:19:09.912+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-27T06:19:09.920+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
